name: money_manager
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  flutter_zoom_drawer: ^2.0.1
  page_transition: ^1.1.7+6
  sqflite: ^2.0.0+3
  path: ^1.8.0
  flutter_slidable: ^0.6.0
  flutter_material_pickers: ^2.1.1
  math_expressions: ^2.1.1
  shared_preferences: ^2.0.5
  image_picker: ^0.7.4
  flutter_spinkit: ^5.0.0
  pie_chart: ^5.0.0
  flutter_cupertino_date_picker: ^1.0.26+2
  percent_indicator: ^3.0.1
  auto_size_text: ^2.1.0
  swipedetector: ^1.2.0
  simple_gesture_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  adaptive_icon_background: "#B71C1C"
  adaptive_icon_foreground: "assets/images/icon-foreground.png"
  ios: true
flutter:

  uses-material-design: true

  assets:
    - assets/categories/expense/
    - assets/categories/income/
    - assets/categories/custom/
    - assets/images/

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-ExtraBold-800.ttf
          weight: 800
        - asset: assets/fonts/FiraSans-Bold-700.ttf
          weight: 700
        - asset: assets/fonts/FiraSans-Medium-500.ttf
          weight: 500
        - asset: assets/fonts/FiraSans-Regular-400.ttf
          weight: 400
        - asset: assets/fonts/FiraSans-SemiBold-600.ttf
          weight: 600
